flag = ["@"] * 62

flag[0] = 'K'
flag[1] = 'C'
flag[2] = 'S'
flag[3] = 'C'
flag[4] = '{'
flag[61] = '}'
flag[24] = 'u'
flag[11] = 'g'
flag[60] = 'g'
flag[37] = 'c'
flag[20] = 'd'


flag[12] = "_"
flag[16] = "_"
flag[26] = "_"
flag[36] = "_"
flag[44] = "_"
flag[49] = "_"

flag[6] = "a"
flag[28] = "a"
flag[33] = "a"
flag[52] = "a"

flag[21] = "e"
flag[30] = "e"
flag[55] = "e"

flag[13] = "f"
flag[23] = "f"
flag[32] = "f"
flag[45] = "f"
flag[50] = "f"

flag[7] = "i"
flag[9] = "i"
flag[58] = "i"

flag[25] = "l"
flag[34] = "l"
flag[35] = "l"
flag[43] = "l"
flag[46] = "l"
flag[51] = "l"

flag[10] = "n"
flag[19] = "n"
flag[39] = "n"
flag[57] = "n"
flag[59] = "n"

flag[14] = "o"
flag[18] = "o"
flag[38] = "o"
flag[42] = "o"
flag[47] = "o"

flag[15] = "r"
flag[22] = "r"
flag[31] = "r"
flag[41] = "r"
flag[56] = "r"

flag[8] = "t"
flag[29] = "t"
flag[40] = "t"
flag[53] = "t"
flag[54] = "t"

flag[5] = "w"
flag[17] = "w"
flag[27] = "w"
flag[48] = "w"

for i in flag: print(end = i)

# KCSC{inrettalf_wolf_lortno@_llafretaw_l@fre@now_r@f@@ni@i@@@g}